ALTER PROCEDURE INSERT_QUESTION
@ORDER INT,
@TEXT NVARCHAR(4000),
@TYPE INT,
@NumberOfSmileyFaces INT
AS
SET NOCOUNT ON

BEGIN TRY
	DECLARE @SUCCESS INT, @SQL_VIOLATION INT, @ERROR INT, @ID INT
	SET @SUCCESS = 1
	SET @SQL_VIOLATION = 2
	SET @ERROR = -1

    INSERT INTO Questions 
    ([Order], [Text], [Type])
    VALUES 
    (@ORDER, @TEXT, @TYPE)
	
	SET @ID = SCOPE_IDENTITY()

	IF(@ID IS NOT NULL)
	BEGIN
	INSERT INTO Smiley_Questions(ID, NumberOfSmileyFaces)
	VALUES (@ID, @NumberOfSmileyFaces)
	
	SELECT @SUCCESS AS ErrorCode, ERROR_MESSAGE() AS ErrorMessage, SCOPE_IDENTITY() AS ID
	RETURN @SUCCESS
	END
	
	--ELSE
	--BEGIN
	--	SELECT @ERROR AS ErrorCode, ERROR_MESSAGE() AS ErrorMessage, SCOPE_IDENTITY() AS ID
	--	RETURN @ERROR
	--END
END TRY
BEGIN CATCH
	SELECT @ERROR AS ErrorCode, ERROR_MESSAGE() AS ErrorMessage, SCOPE_IDENTITY() AS ID
	RETURN @ERROR
END CATCH