ALTER PROCEDURE INSERT_QUESTION
@ORDER INT,
@TEXT NVARCHAR(4000),
@TYPE INT,
@OPUT INT OUTPUT

AS
SET NOCOUNT ON
BEGIN TRY
IF ((SELECT COUNT(ID) FROM Questions WHERE [Order] = @ORDER) = 0)
BEGIN
    INSERT INTO Questions 
    ([Order], [Text], [Type])
    VALUES 
    (@ORDER, @TEXT, @TYPE)
	SET @OPUT = @@IDENTITY
	RETURN 1
END
ELSE
BEGIN
	RETURN 2
END
END TRY
BEGIN CATCH
		RETURN 3
END CATCH