IF OBJECT_ID (N'dbo.CheckIfOrderExist', N'FN') IS NOT NULL  
    DROP FUNCTION dbo.CheckIfOrderExist;  
GO 
CREATE FUNCTION dbo.CheckIfOrderExist (@ORDER INT)
RETURNS TABLE
AS
BEGIN
	DECLARE @SUCCESS INT, @SQL_VIOLATION INT, @ID INT
	SET @SUCCESS = 1
	SET @SQL_VIOLATION = 2


	IF((SELECT COUNT(ID) FROM Questions WHERE [Order] = @ORDER) = 0)
		--RETURN @SUCCESS
		RETURN(
			SELECT @SUCCESS AS ErrorCode, ERROR_MESSAGE() AS ErrorMessage, @ORDER AS ReturnedOrder
		)

	RETURN @SQL_VIOLATION
END;
GO