IF OBJECT_ID (N'dbo.GetIDFromOrder', N'FN') IS NOT NULL  
    DROP FUNCTION dbo.GetIDFromOrder;  
GO 
CREATE FUNCTION dbo.GetIDFromOrder (@ORDER INT)
RETURNS INT
AS
BEGIN
	DECLARE @ID INT
	SET @ID = (SELECT [ID] FROM Questions WHERE [Order] = @ORDER)
	IF(@ID IS NOT NULL)
		RETURN @ID

	RETURN 0
END;
GO