//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyQuestionsConfigurator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AddQuestionFormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddQuestionFormStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SurveyQuestionsConfigurator.AddQuestionFormStrings", typeof(AddQuestionFormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add A Question.
        /// </summary>
        internal static string addAQuestion {
            get {
                return ResourceManager.GetString("addAQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong happened
        ///Please try again or contact your system administrator.
        /// </summary>
        internal static string contactSystemAdministratorError {
            get {
                return ResourceManager.GetString("contactSystemAdministratorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit A Question.
        /// </summary>
        internal static string editAQuestion {
            get {
                return ResourceManager.GetString("editAQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Value Caption:.
        /// </summary>
        internal static string endValueCaption {
            get {
                return ResourceManager.GetString("endValueCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question text can NOT be empty.
        /// </summary>
        internal static string genericQuestionError {
            get {
                return ResourceManager.GetString("genericQuestionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Smiley Faces (2 - 5):.
        /// </summary>
        internal static string numberOfSmileyFaces {
            get {
                return ResourceManager.GetString("numberOfSmileyFaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Stars (1 - 10):.
        /// </summary>
        internal static string numberOfStars {
            get {
                return ResourceManager.GetString("numberOfStars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question order already in use
        ///Try using another one.
        /// </summary>
        internal static string questionOrderAlreadyInUseError {
            get {
                return ResourceManager.GetString("questionOrderAlreadyInUseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question was not found or deleted
        ///Refresh the list and try again.
        /// </summary>
        internal static string questionWasNotFoundOrDeletedError {
            get {
                return ResourceManager.GetString("questionWasNotFoundOrDeletedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider End Value (2 - 100):.
        /// </summary>
        internal static string sliderEndValue {
            get {
                return ResourceManager.GetString("sliderEndValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question text
        ///Start Value caption
        ///End Value caption
        ///Can NOT be empty
        ///
        ///Make sure that end value is larger than start value.
        /// </summary>
        internal static string sliderQuestionError {
            get {
                return ResourceManager.GetString("sliderQuestionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Start Value (1 - 99):.
        /// </summary>
        internal static string sliderStartValue {
            get {
                return ResourceManager.GetString("sliderStartValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong happened
        ///please try again.
        /// </summary>
        internal static string somethingWrongHappenedError {
            get {
                return ResourceManager.GetString("somethingWrongHappenedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Value Caption:.
        /// </summary>
        internal static string startValueCaption {
            get {
                return ResourceManager.GetString("startValueCaption", resourceCulture);
            }
        }
    }
}
